plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.15.2"

title: "Prism IIT"

name: "Prism Exec Board"

description: "Illinois Tech's LGBTQ+ club"

url: "https://bkeeneykid.github.io/prismiit"

logo: "assets/images/pride_logo.png"
masthead_title: " "

footer:
    links:
      - label: "Facebook"
        icon: "fab fa-fw fa-facebook-square"
        url: "https://www.facebook.com/Prism.IIT/"
      - label: "Instagram"
        icon: "fab fa-fw fa-instagram-square"
        url: "https://www.instagram.com/prism.iit/"